// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCoreDemo
{
    public partial class Classes
    {
        public Classes()
        {
            StudentClassRelations = new HashSet<StudentClassRelation>();
        }

        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public DateTime? CreateTime { get; set; }

        public virtual ICollection<StudentClassRelation> StudentClassRelations { get; set; }
    }
}