// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCoreDemo
{
    public partial class Students
    {
        public Students()
        {
            StudentClassRelations = new HashSet<StudentClassRelation>();
        }

        public int StudentId { get; set; }
        public string Name { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual ICollection<StudentClassRelation> StudentClassRelations { get; set; }
    }
}